Let's play around with what we have so far.

First, we'll make a pandas dataframe.

In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

#Add the path to the folder that contains the data. Makes it easier for each of us to use the notebook
path = "/Users/Kyla/Desktop/ErdosDataScienceWork/Project/data/"
#path = "/Users/es/Projects/erdo/sumo/Erdos-Institute-Fall-2024-Project-Sumo/data/"

df1983 = pd.read_csv(path+str(1983)+'.csv')
df1984 = pd.read_csv(path+str(1984)+'.csv')

df = df1983
for year in range(1984,2020):
    year = str(year)
    dfyear = pd.read_csv(path+year+'.csv')
    df = pd.concat([df, dfyear], axis=0, ignore_index=True)

In [2]:
from sumo import *

df = add_col_for_penultimate_day_7_wins(df)
df = get_ordinal_rank(df)
df = get_how_long_in_sumo(df)

In [4]:
df = df.sort_index()

In [11]:
df # This is our big data frame.

,index,basho,day,rikishi1_id,rikishi1_rank,rikishi1_shikona,rikishi1_result,rikishi1_win,kimarite,rikishi2_id,...,rikishi2_win,rikishi1_wins_in_tournament,rikishi2_wins_in_tournament,rikishi1_penultimate_day_7_wins,rikishi2_penultimate_day_7_wins,r1_sort_rank,r1_ord_rank,year,rikishi1_years_in_sumo,rikishi2_years_in_sumo
0,0,1983.01,1,4140,J13w,Chikubayama,0-1 (7-8),0,yorikiri,4306,...,1,0,1,None,None,6132,78,1983,1,1
1,1,1983.01,1,4306,Ms1e,Ofuji,1-0 (6-1),1,yorikiri,4140,...,0,1,0,None,None,7011,81,1983,1,1
2,2,1983.01,1,1337,J12w,Tochitsukasa,1-0 (9-6),1,oshidashi,4323,...,0,1,0,None,None,6122,76,1983,1,1
3,3,1983.01,1,4323,J13e,Shiraiwa,0-1 (3-12),0,oshidashi,1337,...,1,0,1,None,None,6131,77,1983,1,1
4,4,1983.01,1,4097,J12e,Tamakiyama,0-1 (8-7),0,yorikiri,4319,...,1,0,1,None,None,6121,75,1983,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214783,4985,2019.09,15,12210,S1e,Mitakeumi,12-3,1,yorikiri,12055,...,0,12,8,None,None,3011,11,2019,5,7
214784,4986,2019.09,15,6468,O1w,Goeido,10-5,1,yorikiri,6599,...,0,10,6,None,None,2012,6,2019,14,13
214785,4987,2019.09,15,6599,O2e,Tochinoshin,6-9,0,yorikiri,6468,...,1,6,10,None,None,2021,7,2019,13,14
214786,4988,2019.09,16,12191,S1w,Takakeisho,(12-3),0,yorikiri,12210,...,1,12,12,None,None,3012,12,2019,4,5
214787,4989,2019.09,16,12210,S1e,Mitakeumi,(12-3),1,yorikiri,12191,...,0,12,12,None,None,3011,11,2019,5,4

The data frame below only includes rows where (1) it's the 14th day and (2) rikishi1 has seven wins.

In [ ]:
pen_day_7_wins_df = df[df['rikishi1_penultimate_day_7_wins'] == True]
pen_day_7_wins_df

In [9]:
pen_day_7_wins_df['rikishi1_win'].mean()

np.float64(0.538917089678511)

In [10]:
df['rikishi1_win'].mean()

np.float64(0.5)

We have a problem. This is 0.5 because each row shows up twice. We need to make a data frame where each *match* shows up once.

In [ ]:
df_even_indexed_rows = df.iloc[::2]
df_even_indexed_rows # This data frame only contains the even-indexed rows.

,index,basho,day,rikishi1_id,rikishi1_rank,rikishi1_shikona,rikishi1_result,rikishi1_win,kimarite,rikishi2_id,...,rikishi2_win,rikishi1_wins_in_tournament,rikishi2_wins_in_tournament,rikishi1_penultimate_day_7_wins,rikishi2_penultimate_day_7_wins,r1_sort_rank,r1_ord_rank,year,rikishi1_years_in_sumo,rikishi2_years_in_sumo
0,0,1983.01,1,4140,J13w,Chikubayama,0-1 (7-8),0,yorikiri,4306,...,1,0,1,None,None,6132,78,1983,1,1
2,2,1983.01,1,1337,J12w,Tochitsukasa,1-0 (9-6),1,oshidashi,4323,...,0,1,0,None,None,6122,76,1983,1,1
4,4,1983.01,1,4097,J12e,Tamakiyama,0-1 (8-7),0,yorikiri,4319,...,1,0,1,None,None,6121,75,1983,1,1
6,6,1983.01,1,4109,J10w,Kotogatake,0-1 (7-8),0,tsukidashi,4129,...,1,0,1,None,None,6102,72,1983,1,1
8,8,1983.01,1,4111,J10e,Zaonishiki,0-1 (4-11),0,hatakikomi,4130,...,1,0,1,None,None,6101,71,1983,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214778,4980,2019.09,15,11784,M6w,Myogiryu,8-5-2,1,yorikiri,12094,...,0,8,9,None,None,5062,30,2019,11,5
214780,4982,2019.09,15,6463,M8e,Okinoumi,11-4,0,oshidashi,12191,...,1,11,12,None,None,5081,33,2019,11,4
214782,4984,2019.09,15,12055,K1w,Endo,8-7,0,yorikiri,12210,...,1,8,12,None,None,4012,16,2019,7,5
214784,4986,2019.09,15,6468,O1w,Goeido,10-5,1,yorikiri,6599,...,0,10,6,None,None,2012,6,2019,14,13
214786,4988,2019.09,16,12191,S1w,Takakeisho,(12-3),0,yorikiri,12210,...,1,12,12,None,None,3012,12,2019,4,5

Let's try what we did above again. How often does rikishi1 win? How often does rikishi1 when their record is 7-7 on day 14?

In [21]:
df_even_indexed_rows['rikishi1_win'].mean()

np.float64(0.5178501592267725)

In [22]:
df_even_indexed_rows_pen_day_7_wins = df_even_indexed_rows[df_even_indexed_rows['rikishi1_penultimate_day_7_wins'] == True]
df_even_indexed_rows_pen_day_7_wins

,index,basho,day,rikishi1_id,rikishi1_rank,rikishi1_shikona,rikishi1_result,rikishi1_win,kimarite,rikishi2_id,...,rikishi2_win,rikishi1_wins_in_tournament,rikishi2_wins_in_tournament,rikishi1_penultimate_day_7_wins,rikishi2_penultimate_day_7_wins,r1_sort_rank,r1_ord_rank,year,rikishi1_years_in_sumo,rikishi2_years_in_sumo
802,802,1983.01,14,4097,J12e,Tamakiyama,7-7 (8-7),1,oshidashi,4129,...,0,7,3,True,False,6121,75,1983,1,1
810,810,1983.01,14,4109,J10w,Kotogatake,7-7 (7-8),0,tsukidashi,4316,...,1,7,8,True,False,6102,72,1983,1,1
814,814,1983.01,14,1385,J6w,Tochiakagi,7-7 (8-7),1,oshidashi,4322,...,0,7,5,True,False,6062,64,1983,1,1
836,836,1983.01,14,1375,M6e,Masudayama,7-7 (8-7),1,oshidashi,4103,...,0,7,4,True,False,5061,29,1983,1,1
1720,1720,1983.03,14,1380,M11w,Hidanohana,7-7 (8-7),1,hatakikomi,4131,...,0,7,8,True,False,5112,40,1983,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214672,4874,2019.09,14,12425,J4e,Yago,7-7 (8-7),1,hatakikomi,12470,...,0,7,7,True,True,6041,59,2019,3,1
214676,4878,2019.09,14,11726,J3e,Tokushoryu,7-7 (8-7),1,tottari,12270,...,0,7,9,True,False,6031,57,2019,10,1
214686,4888,2019.09,14,12051,M15e,Ishiura,7-7 (8-7),0,oshidashi,12370,...,1,7,8,True,False,5151,47,2019,6,2
214698,4900,2019.09,14,7153,M7w,Kotoeko,7-7 (7-8),1,hikiotoshi,11845,...,0,7,5,True,False,5072,32,2019,6,6
214710,4912,2019.09,14,5944,M4e,Tamawashi,7-7 (7-8),0,oshidashi,12239,...,1,7,8,True,False,5041,25,2019,13,4

We will need the number of observations of each outcome for the test, not just the proportion.

In [28]:
df_even_indexed_rows_pen_day_7_wins['rikishi1_win'].mean()
df_even_indexed_rows_pen_day_7_wins['rikishi1_win'].sum()

np.int64(650)

This data frame will have all rows where the day is not 14 and all rows where the day is 14, but the number of rikishi1 wins is NOT 7.

In [24]:
df_everything_else = df_even_indexed_rows[df_even_indexed_rows['rikishi1_penultimate_day_7_wins'] != True]
df_everything_else

,index,basho,day,rikishi1_id,rikishi1_rank,rikishi1_shikona,rikishi1_result,rikishi1_win,kimarite,rikishi2_id,...,rikishi2_win,rikishi1_wins_in_tournament,rikishi2_wins_in_tournament,rikishi1_penultimate_day_7_wins,rikishi2_penultimate_day_7_wins,r1_sort_rank,r1_ord_rank,year,rikishi1_years_in_sumo,rikishi2_years_in_sumo
0,0,1983.01,1,4140,J13w,Chikubayama,0-1 (7-8),0,yorikiri,4306,...,1,0,1,None,None,6132,78,1983,1,1
2,2,1983.01,1,1337,J12w,Tochitsukasa,1-0 (9-6),1,oshidashi,4323,...,0,1,0,None,None,6122,76,1983,1,1
4,4,1983.01,1,4097,J12e,Tamakiyama,0-1 (8-7),0,yorikiri,4319,...,1,0,1,None,None,6121,75,1983,1,1
6,6,1983.01,1,4109,J10w,Kotogatake,0-1 (7-8),0,tsukidashi,4129,...,1,0,1,None,None,6102,72,1983,1,1
8,8,1983.01,1,4111,J10e,Zaonishiki,0-1 (4-11),0,hatakikomi,4130,...,1,0,1,None,None,6101,71,1983,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214778,4980,2019.09,15,11784,M6w,Myogiryu,8-5-2,1,yorikiri,12094,...,0,8,9,None,None,5062,30,2019,11,5
214780,4982,2019.09,15,6463,M8e,Okinoumi,11-4,0,oshidashi,12191,...,1,11,12,None,None,5081,33,2019,11,4
214782,4984,2019.09,15,12055,K1w,Endo,8-7,0,yorikiri,12210,...,1,8,12,None,None,4012,16,2019,7,5
214784,4986,2019.09,15,6468,O1w,Goeido,10-5,1,yorikiri,6599,...,0,10,6,None,None,2012,6,2019,14,13
214786,4988,2019.09,16,12191,S1w,Takakeisho,(12-3),0,yorikiri,12210,...,1,12,12,None,None,3012,12,2019,4,5

In [27]:
df_everything_else['rikishi1_win'].mean()
df_everything_else['rikishi1_win'].sum()

np.int64(54964)

Okay, let's do a z-test for difference in proportions. One set of observations will be matches where it's the 14th day and rikishi1 has 7 wins. The other set of observations will be the every other row in the even-indexed dat a frame.

In [30]:
from statsmodels.stats.proportion import proportions_ztest

In [31]:
# Sample data: successes and sample sizes for each group
success_14_day_7_wins = 650  # number of wins of wrestlers who have 7 wins on the 14th day
nobs_14_day_7_wins = 1188    # number of observations of wrestlers who have 7 wins on the 14th day
success_other = 54964  # number of wins of wrestlers who are not in this situation
nobs_other = 106206    # number of observations of wrestlers who are not in this situation

# Define the counts of successes and the number of trials
counts = [success_14_day_7_wins, success_other]
nobs = [nobs_14_day_7_wins, nobs_other]

# Perform the two-proportion z-test
stat, p_value = proportions_ztest(count=counts, nobs=nobs, alternative='two-sided')

print("Z-test statistic:", stat)
print("p-value:", p_value)

Z-test statistic: 2.031508698282944
p-value: 0.042203418076244135

Hahaha, Freakonomics was right, this is a significant result.

Now, perhaps we should be more careful about this. Instead of using all other data for our second set of observations, perhaps we should use only 14th day data. Let's try that next.

In [32]:
df_day_14_evens = df_even_indexed_rows[df_even_indexed_rows['day'] == 14]

This is the data frame with double matches removed and only showing day 14.

In [33]:
df_day_14_evens

,index,basho,day,rikishi1_id,rikishi1_rank,rikishi1_shikona,rikishi1_result,rikishi1_win,kimarite,rikishi2_id,...,rikishi2_win,rikishi1_wins_in_tournament,rikishi2_wins_in_tournament,rikishi1_penultimate_day_7_wins,rikishi2_penultimate_day_7_wins,r1_sort_rank,r1_ord_rank,year,rikishi1_years_in_sumo,rikishi2_years_in_sumo
802,802,1983.01,14,4097,J12e,Tamakiyama,7-7 (8-7),1,oshidashi,4129,...,0,7,3,True,False,6121,75,1983,1,1
804,804,1983.01,14,1317,Ms2w,Hananokuni,4-3,1,yorikiri,4319,...,0,4,5,False,False,7022,84,1983,1,1
806,806,1983.01,14,4111,J10e,Zaonishiki,4-10 (4-11),0,oshidashi,4140,...,1,4,6,False,False,6101,71,1983,1,1
808,808,1983.01,14,1302,J9e,Takamisugi,4-10 (5-10),0,yorikiri,4130,...,1,4,7,False,True,6091,69,1983,1,1
810,810,1983.01,14,4109,J10w,Kotogatake,7-7 (7-8),0,tsukidashi,4316,...,1,7,8,True,False,6102,72,1983,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214714,4916,2019.09,14,11728,M8w,Takarafuji,9-5 (9-6),0,tsukidashi,12094,...,1,9,9,False,False,5082,34,2019,10,5
214716,4918,2019.09,14,6463,M8e,Okinoumi,11-3 (11-4),1,yorikiri,12055,...,0,11,8,False,False,5081,33,2019,11,7
214718,4920,2019.09,14,6594,M5w,Ryuden,6-8 (7-8),0,oshidashi,12191,...,1,6,11,False,False,5052,28,2019,8,4
214720,4922,2019.09,14,6468,O1w,Goeido,9-5 (10-5),0,tsukiotoshi,12210,...,1,9,11,False,False,2012,6,2019,14,5
214722,4924,2019.09,14,6599,O2e,Tochinoshin,6-8 (6-9),0,yorikiri,11784,...,1,6,7,False,True,2021,7,2019,13,11

Now let's only keep the rows where the wrestler didn't have 7 wins on the fourteenth day.

In [38]:
df_14_day_not_7_wins = df_day_14_evens[df_day_14_evens['rikishi1_penultimate_day_7_wins'] == False]
df_14_day_not_7_wins

,index,basho,day,rikishi1_id,rikishi1_rank,rikishi1_shikona,rikishi1_result,rikishi1_win,kimarite,rikishi2_id,...,rikishi2_win,rikishi1_wins_in_tournament,rikishi2_wins_in_tournament,rikishi1_penultimate_day_7_wins,rikishi2_penultimate_day_7_wins,r1_sort_rank,r1_ord_rank,year,rikishi1_years_in_sumo,rikishi2_years_in_sumo
804,804,1983.01,14,1317,Ms2w,Hananokuni,4-3,1,yorikiri,4319,...,0,4,5,False,False,7022,84,1983,1,1
806,806,1983.01,14,4111,J10e,Zaonishiki,4-10 (4-11),0,oshidashi,4140,...,1,4,6,False,False,6101,71,1983,1,1
808,808,1983.01,14,1302,J9e,Takamisugi,4-10 (5-10),0,yorikiri,4130,...,1,4,7,False,True,6091,69,1983,1,1
812,812,1983.01,14,1347,J6e,Itai,10-4 (11-4),1,tsukidashi,4318,...,0,10,6,False,False,6061,63,1983,1,1
816,816,1983.01,14,1332,J4w,Sakahoko,9-5 (9-6),1,yorikiri,4311,...,0,9,8,False,False,6042,60,1983,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214714,4916,2019.09,14,11728,M8w,Takarafuji,9-5 (9-6),0,tsukidashi,12094,...,1,9,9,False,False,5082,34,2019,10,5
214716,4918,2019.09,14,6463,M8e,Okinoumi,11-3 (11-4),1,yorikiri,12055,...,0,11,8,False,False,5081,33,2019,11,7
214718,4920,2019.09,14,6594,M5w,Ryuden,6-8 (7-8),0,oshidashi,12191,...,1,6,11,False,False,5052,28,2019,8,4
214720,4922,2019.09,14,6468,O1w,Goeido,9-5 (10-5),0,tsukiotoshi,12210,...,1,9,11,False,False,2012,6,2019,14,5
214722,4924,2019.09,14,6599,O2e,Tochinoshin,6-8 (6-9),0,yorikiri,11784,...,1,6,7,False,True,2021,7,2019,13,11

In [39]:
df_14_day_not_7_wins['rikishi1_win'].sum()

np.int64(2939)

We have 2939 matches where rikishi1 won on the fourteenth day but wasn't at 7 wins going in to the day.

Okay, attempt two. We'll leave our first observation set the same and use the 5897 rows we have where it's day 14 and the wrestler is not at 7 wins for the second observation set. Note that we have 2939 wins here.

In [41]:
# Sample data: successes and sample sizes for each group
success_14_day_7_wins = 650  # number of wins of wrestlers who have 7 wins on the 14th day
nobs_14_day_7_wins = 1188    # number of observations of wrestlers who have 7 wins on the 14th day
success_other = 2939  # number of day 14 wins of wrestlers who are not in this situation
nobs_other = 5897    # number of day 14 observations of wrestlers who are not in this situation

# Define the counts of successes and the number of trials
counts = [success_14_day_7_wins, success_other]
nobs = [nobs_14_day_7_wins, nobs_other]

# Perform the two-proportion z-test
stat, p_value = proportions_ztest(count=counts, nobs=nobs, alternative='two-sided')

print("Z-test statistic:", stat)
print("p-value:", p_value)

Z-test statistic: 3.06610695600101
p-value: 0.0021686572363084234

Holy moly. I wonder if I did something wrong. This p-value is **tiny**!