First, we'll make a pandas dataframe. Let's just use the 1983 data for now. Since I know how to concatenate data frames now, we can deal the rest of the data later.

In [1]:
import pandas as pd

df1983 = pd.read_csv('/Users/Kyla/Desktop/ErdosDataScienceWork/Project/data/1983.csv')

In [2]:
df1983

,index,basho,day,rikishi1_id,rikishi1_rank,rikishi1_shikona,rikishi1_result,rikishi1_win,kimarite,rikishi2_id,rikishi2_rank,rikishi2_shikona,rikishi2_result,rikishi2_win
0,0,1983.01,1,4140,J13w,Chikubayama,0-1 (7-8),0,yorikiri,4306,Ms1e,Ofuji,1-0 (6-1),1
1,1,1983.01,1,4306,Ms1e,Ofuji,1-0 (6-1),1,yorikiri,4140,J13w,Chikubayama,0-1 (7-8),0
2,2,1983.01,1,1337,J12w,Tochitsukasa,1-0 (9-6),1,oshidashi,4323,J13e,Shiraiwa,0-1 (3-12),0
3,3,1983.01,1,4323,J13e,Shiraiwa,0-1 (3-12),0,oshidashi,1337,J12w,Tochitsukasa,1-0 (9-6),1
4,4,1983.01,1,4097,J12e,Tamakiyama,0-1 (8-7),0,yorikiri,4319,J11w,Harunafuji,1-0 (5-10),1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5483,5483,1983.11,15,4104,Y1e,Takanosato,13-2,0,yorikiri,1354,Y1w,Chiyonofuji,14-1,1
5484,5484,1983.11,16,1348,J4w,Jingaku,(11-4),0,sotogake,1378,J1w,Hoo,(11-4),1
5485,5485,1983.11,16,1378,J1w,Hoo,(11-4),1,sotogake,1348,J4w,Jingaku,(11-4),0
5486,5486,1983.11,16,1287,J12w,Konishiki,(11-4),0,yorikiri,1378,J1w,Hoo,(11-4),1
5487,5487,1983.11,16,1378,J1w,Hoo,(11-4),1,yorikiri,1287,J12w,Konishiki,(11-4),0

Here's a function that tells us actual rank given a row of the data frame above. This is just a prototype to figure out what's going wrong.

In [43]:
def nonsumorank(row):
    string1 = 'Ms1e'
    if row['rikishi1_rank'] == string1:
        return 0
    else:
        return 1

In [44]:
df1983['rikishi1_nonsumorank'] = df1983.apply(nonsumorank, axis=1)

In [45]:
df1983

,index,basho,day,rikishi1_id,rikishi1_rank,rikishi1_shikona,rikishi1_result,rikishi1_win,kimarite,rikishi2_id,rikishi2_rank,rikishi2_shikona,rikishi2_result,rikishi2_win,rikishi1_nonsumorank
0,0,1983.01,1,4140,J13w,Chikubayama,0-1 (7-8),0,yorikiri,4306,Ms1e,Ofuji,1-0 (6-1),1,1
1,1,1983.01,1,4306,Ms1e,Ofuji,1-0 (6-1),1,yorikiri,4140,J13w,Chikubayama,0-1 (7-8),0,0
2,2,1983.01,1,1337,J12w,Tochitsukasa,1-0 (9-6),1,oshidashi,4323,J13e,Shiraiwa,0-1 (3-12),0,1
3,3,1983.01,1,4323,J13e,Shiraiwa,0-1 (3-12),0,oshidashi,1337,J12w,Tochitsukasa,1-0 (9-6),1,1
4,4,1983.01,1,4097,J12e,Tamakiyama,0-1 (8-7),0,yorikiri,4319,J11w,Harunafuji,1-0 (5-10),1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5483,5483,1983.11,15,4104,Y1e,Takanosato,13-2,0,yorikiri,1354,Y1w,Chiyonofuji,14-1,1,1
5484,5484,1983.11,16,1348,J4w,Jingaku,(11-4),0,sotogake,1378,J1w,Hoo,(11-4),1,1
5485,5485,1983.11,16,1378,J1w,Hoo,(11-4),1,sotogake,1348,J4w,Jingaku,(11-4),0,1
5486,5486,1983.11,16,1287,J12w,Konishiki,(11-4),0,yorikiri,1378,J1w,Hoo,(11-4),1,1
5487,5487,1983.11,16,1378,J1w,Hoo,(11-4),1,yorikiri,1287,J12w,Konishiki,(11-4),0,1